<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <AssemblyName>CxChat</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS0618;CS0672;CS0067;CS0219;CS0168;CS0169</NoWarn>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>release\</OutputPath>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\赛尔号纯净插件-反编译源码\CxChat\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="LabApi"><HintPath>lib\LabApi.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>lib\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="CommandSystem.Core"><HintPath>lib\CommandSystem.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mirror"><HintPath>lib\Mirror.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="HintServiceMeow"><HintPath>lib\HintServiceMeow.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>lib\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp-firstpass"><HintPath>lib\Assembly-CSharp-firstpass.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>lib\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>lib\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>